#ifndef KLIB_KONGKONG_NUMERICS_UNSIGNEDINTEGER16BYTE_H
#define KLIB_KONGKONG_NUMERICS_UNSIGNEDINTEGER16BYTE_H

// クラスはこのヘッダーで定義
#include "Kongkong.Numerics.Integer16Byte.h"

#endif //!KLIB_KONGKONG_NUMERICS_UNSIGNEDINTEGER16BYTE_H